export const DRAW_STATUS = Object.freeze({
	IDLE: 0,
	DRAWING: 1,
});

export const COMMANDS = Object.freeze({
	START_DRAW: 1,
	END_DRAW: 2,
	CHAT_TYPING: 3,
	CHAT_INPUT: 4,
	CLIENT_CLOSED: 95,
	MASTER_SHOULD_SHARE: 96,
	REGISTER_INFO: 97,
	REGISTER_MASTER: 98,
	REGISTER_SLAVE: 99,
});
